### ISSUE TITLE
Unable to Use ResNet Model

### ISSUE THREAD

**Issue by njcich** [matej-ulicny/harmonic-networks#4]
I'm attempting to integrate the Harmonic ResNet 50 model with another network to compare its performance, but when I try to import resnet50, I get the following error:
`ModuleNotFoundError: no module named 'utils'`

It doesn't seem like `utils.py` or `harmonic.py` are in the same folder as `resnet.py`, which is causing this issue. Do you know how I could solve this problem? Thanks!

**Comment by matej-ulicny** [comment]
Hi, did you install the the package via `python setup.py develop`? That will let you import definitions in `harmonic.py` anywhere. If you have moved the `resnet.py` into another location and you have problem importing the utils you can move `imagenet/utils.py` into your working directory or as an alternative you can copy the `load_pretrained()` function directly into the `resnet.py`.

**Comment by njcich** [comment]
I had moved `resnet.py` into a different location after running `setup.py`, but copying the `load_pretrained()` function directly into `resnet.py` worked. Thanks!
